### PR TITLE
more python fixes

### PR DESCRIPTION
**Pull request by fchapoton**
* more python fixes in print, raise, exception, etc

### CODE REVIEW

**Comment by novoselt** [comment]
There are conflicts and can we please keep separate python3 fixes from logo files? Regarding logos - "new ones" seem to be already in place, but ever since they were added they had wrong names (the correct names are sagemathcell-logo.*) and so were not used. It seems to me also that their size was wrong before while your new branch has it right.

**Comment by fchapoton** [comment]
ok, here is a new branch, without logos and without conflict, I hope

**Comment by novoselt** [comment]
Thank you, and thank you for weeding out all these little things!

**Comment by fchapoton** [comment]
By the way, did you try to launch sagecell with python3 ? Probably not yet working, but who knows..

**Comment by novoselt** [comment]
I didn't yet, but plan to work on it in the summer (if any work is actually required ;-)).

**Comment by slel** [comment]
Are you talking about adding "sage-py3" to the list of languages, which
currently has: sage, GAP, GP, HTML, Maxima, Octave, Python, R, Singular,
or about running SageCell itself with python3?

**Comment by fchapoton** [comment]
I am talking about running sagecell itself with python3, thanks to the
changes just done in this branch..

Le dim. 14 avr. 2019 à 22:23, Samuel Lelièvre <notifications@github.com> a
écrit :

**Comment by slel** [comment]
Okay, I opened #516 about sage-py3.

**Pull request merged**
