### PR TITLE
adding Sponsor link

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by fchapoton** [comment]
not sure if the embedded iframe will work or not

**Comment by fchapoton** [comment]
any comment, Andrey ?

**Comment by novoselt** [comment]
Yes, I was thinking about it. It seems to me that instead of another paragraph it makes more sense to add it to the first one under "About" that mentions SageMath, line 7.

**Comment by fchapoton** [comment]
ok, like this ?

**Comment by novoselt** [comment]
Yes!

**Pull request merged**
